"""LLM-powered attack planning module."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum

from core.config import Config


class Priority(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class AttackStep:
    """A single step in the attack plan."""

    id: int
    phase: str
    action: str
    tool: str
    command: str
    rationale: str
    priority: Priority = Priority.MEDIUM
    depends_on: list[int] = field(default_factory=list)
    completed: bool = False
    result_summary: str = ""


@dataclass
class AttackPlan:
    """Complete attack plan generated by the LLM."""

    target: str
    steps: list[AttackStep] = field(default_factory=list)
    summary: str = ""

    def pending_steps(self) -> list[AttackStep]:
        return [s for s in self.steps if not s.completed]

    def next_step(self) -> AttackStep | None:
        for step in self.steps:
            if not step.completed:
                deps_met = all(
                    self.steps[d - 1].completed for d in step.depends_on if d <= len(self.steps)
                )
                if deps_met:
                    return step
        return None


PLAN_SYSTEM_PROMPT = """You are Vulcan's attack planner — an expert penetration tester.
Given reconnaissance data about a target, generate a prioritized attack plan.
Output valid JSON with this structure:
{
  "summary": "Brief overview of the attack strategy",
  "steps": [
    {
      "id": 1,
      "phase": "recon|scanning|exploitation|post-exploitation",
      "action": "Description of what to do",
      "tool": "tool_name",
      "command": "exact command to run",
      "rationale": "Why this step matters",
      "priority": "critical|high|medium|low",
      "depends_on": []
    }
  ]
}
Only include steps that are safe, legal (within scope), and relevant.
Prioritize by likelihood of finding vulnerabilities and impact."""


class Planner:
    """Generates attack plans using LLM reasoning over recon data."""

    def __init__(self, config: Config):
        self.config = config
        self._client = None

    def _get_client(self):
        if self._client:
            return self._client

        if self.config.llm_provider == "claude":
            import anthropic
            self._client = anthropic.Anthropic(api_key=self.config.anthropic_api_key)
        elif self.config.llm_provider == "smartllm":
            self._client = "smartllm"  # sentinel — we shell out to the binary
        else:
            import openai
            self._client = openai.OpenAI(api_key=self.config.openai_api_key)
        return self._client

    def generate_plan(self, target: str, recon_data: dict) -> AttackPlan:
        """Generate an attack plan from reconnaissance data."""
        user_prompt = (
            f"Target: {target}\n\n"
            f"Reconnaissance Data:\n{json.dumps(recon_data, indent=2, default=str)}\n\n"
            "Generate a penetration testing attack plan based on this data."
        )

        raw = self._call_llm(PLAN_SYSTEM_PROMPT, user_prompt)
        return self._parse_plan(target, raw)

    def replan(self, plan: AttackPlan, new_findings: dict) -> AttackPlan:
        """Adjust the plan based on new findings discovered during execution."""
        user_prompt = (
            f"Target: {plan.target}\n\n"
            f"Current plan summary: {plan.summary}\n"
            f"Completed steps: {[s.action for s in plan.steps if s.completed]}\n"
            f"New findings:\n{json.dumps(new_findings, indent=2, default=str)}\n\n"
            "Update the attack plan. Keep completed steps, adjust or add new ones."
        )

        raw = self._call_llm(PLAN_SYSTEM_PROMPT, user_prompt)
        return self._parse_plan(plan.target, raw)

    def _call_llm(self, system: str, user: str) -> str:
        client = self._get_client()

        if self.config.llm_provider == "claude":
            resp = client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=4096,
                system=system,
                messages=[{"role": "user", "content": user}],
            )
            return resp.content[0].text
        if self.config.llm_provider == "smartllm":
            return self._call_smartllm(system, user)
        resp = client.chat.completions.create(
            model="gpt-4o",
            max_tokens=4096,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        )
        return resp.choices[0].message.content

    def _call_smartllm(self, system: str, user: str) -> str:
        import subprocess

        prompt = (
            f"[SYSTEM]\n{system}\n\n"
            f"[USER]\n{user}\n\n"
            "[ASSISTANT]\nReply with ONLY the JSON object — no prose, no code fences.\n"
        )
        try:
            proc = subprocess.run(
                [
                    self.config.smartllm_binary,
                    prompt,
                    "--task", "reason",
                    "--keep-alive", "24h",
                    "--max-tokens", "4096",
                ],
                capture_output=True,
                text=True,
                timeout=self.config.cmd_timeout,
            )
        except FileNotFoundError:
            raise RuntimeError(
                f"smart-llm binary not found at '{self.config.smartllm_binary}'. "
                "Install it or set VULCAN_SMARTLLM_BIN."
            )
        if proc.returncode != 0:
            raise RuntimeError(f"smart-llm exited {proc.returncode}: {proc.stderr.strip()}")
        return proc.stdout.strip()

    @staticmethod
    def _parse_plan(target: str, raw: str) -> AttackPlan:
        """Parse LLM JSON output into an AttackPlan."""
        # Extract JSON from potential markdown code fences
        text = raw.strip()
        if "```" in text:
            start = text.index("```") + 3
            if text[start:].startswith("json"):
                start += 4
            end = text.index("```", start)
            text = text[start:end].strip()

        data = json.loads(text)
        steps = []
        for s in data.get("steps", []):
            steps.append(
                AttackStep(
                    id=s["id"],
                    phase=s.get("phase", ""),
                    action=s.get("action", ""),
                    tool=s.get("tool", ""),
                    command=s.get("command", ""),
                    rationale=s.get("rationale", ""),
                    priority=Priority(s.get("priority", "medium")),
                    depends_on=s.get("depends_on", []),
                )
            )

        return AttackPlan(target=target, steps=steps, summary=data.get("summary", ""))
